name: "Pull request to v2.x/master with commits to master"
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  V2_BRANCH: v2.x/master
  MERGE_TO_V2_BRANCH: explorer-api-common/v2/merge

jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare branch to merge
        run: |
          git config --global user.email "zowe-robot@users.noreply.github.com"
          git config --global user.name "Zowe Robot"
          git config --global pull.rebase false
          git checkout ${{ env.MERGE_TO_V2_BRANCH }} || git checkout -b ${{ env.MERGE_TO_V2_BRANCH }}
          git pull origin master

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          script: |
            try {
              await github.rest.pulls.create({
                owner: 'zowe',
                repo: 'explorer-api-common',
                title: 'Automatic PR to ${{ env.V2_BRANCH }} from master',
                body: 'Automatically prepared PR for merging into the V2 branch',
                head: '${{ env.V2_BRANCH }}',
                base: '${{ env.MERGE_TO_V2_BRANCH }}'
              });
            } catch (ex) {
              if (
                ex.message &&
                ex.message.includes("No commits between ${{ env.MERGE_TO_V2_BRANCH }} and ${{ env.V2_BRANCH }}")
              ) {
                console.log("No commits to make PR for, ending without error");
              } else {
                throw ex;
              }
            }
